name: Docker Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t flask-app .
      - name: Install dependencies
        run: pip install flask pytest

      - name: Run tests
        run: pytest
